/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Anderson
 */
public class AlterarSenha_medico extends javax.swing.JFrame {

    /**
     * Creates new form AlterarSenha_medico
     */
    public AlterarSenha_medico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jLabelAlterarSenha_medico = new javax.swing.JLabel();
        jLabelSenhaAtual_AlterarSenha_medico = new javax.swing.JLabel();
        jTextFieldSenhaAtual_AlterarSenha_medico = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabelNovaSenha_AlterarSenha_medico = new javax.swing.JLabel();
        jLabelConfirmarNovaSenha_AlterarSenha_medico = new javax.swing.JLabel();
        jTextFieldConfirmarNovaSenha_AlterarSenha_medico = new javax.swing.JTextField();
        jButtonSalvar_AlterarSenha_medico = new javax.swing.JButton();
        jButtonCancelar_AlterarSenha_medico = new javax.swing.JButton();
        jButtonLimpar_AlterarSenha_medico = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelAlterarSenha_medico.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelAlterarSenha_medico.setText("Alterar Senha");
        getContentPane().add(jLabelAlterarSenha_medico);
        jLabelAlterarSenha_medico.setBounds(10, 0, 150, 40);

        jLabelSenhaAtual_AlterarSenha_medico.setText("Senha Atual:");
        getContentPane().add(jLabelSenhaAtual_AlterarSenha_medico);
        jLabelSenhaAtual_AlterarSenha_medico.setBounds(10, 40, 80, 30);

        jTextFieldSenhaAtual_AlterarSenha_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSenhaAtual_AlterarSenha_medicoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSenhaAtual_AlterarSenha_medico);
        jTextFieldSenhaAtual_AlterarSenha_medico.setBounds(10, 70, 380, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 130, 380, 30);

        jLabelNovaSenha_AlterarSenha_medico.setText("Nova Senha:");
        getContentPane().add(jLabelNovaSenha_AlterarSenha_medico);
        jLabelNovaSenha_AlterarSenha_medico.setBounds(10, 100, 140, 30);

        jLabelConfirmarNovaSenha_AlterarSenha_medico.setText("Confirmar Nova Senha:");
        getContentPane().add(jLabelConfirmarNovaSenha_AlterarSenha_medico);
        jLabelConfirmarNovaSenha_AlterarSenha_medico.setBounds(10, 170, 190, 30);
        getContentPane().add(jTextFieldConfirmarNovaSenha_AlterarSenha_medico);
        jTextFieldConfirmarNovaSenha_AlterarSenha_medico.setBounds(10, 200, 380, 30);

        jButtonSalvar_AlterarSenha_medico.setText("Salvar");
        getContentPane().add(jButtonSalvar_AlterarSenha_medico);
        jButtonSalvar_AlterarSenha_medico.setBounds(130, 260, 80, 30);

        jButtonCancelar_AlterarSenha_medico.setText("Cancelar");
        getContentPane().add(jButtonCancelar_AlterarSenha_medico);
        jButtonCancelar_AlterarSenha_medico.setBounds(310, 260, 80, 30);

        jButtonLimpar_AlterarSenha_medico.setText("Limpar");
        getContentPane().add(jButtonLimpar_AlterarSenha_medico);
        jButtonLimpar_AlterarSenha_medico.setBounds(220, 260, 80, 30);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSenhaAtual_AlterarSenha_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSenhaAtual_AlterarSenha_medicoActionPerformed
         
    }//GEN-LAST:event_jTextFieldSenhaAtual_AlterarSenha_medicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarSenha_medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarSenha_medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarSenha_medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarSenha_medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarSenha_medico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCancelar_AlterarSenha_medico;
    private javax.swing.JButton jButtonLimpar_AlterarSenha_medico;
    private javax.swing.JButton jButtonSalvar_AlterarSenha_medico;
    private javax.swing.JLabel jLabelAlterarSenha_medico;
    private javax.swing.JLabel jLabelConfirmarNovaSenha_AlterarSenha_medico;
    private javax.swing.JLabel jLabelNovaSenha_AlterarSenha_medico;
    private javax.swing.JLabel jLabelSenhaAtual_AlterarSenha_medico;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldConfirmarNovaSenha_AlterarSenha_medico;
    private javax.swing.JTextField jTextFieldSenhaAtual_AlterarSenha_medico;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
