/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;



/**
 *
 * @author Anderson
 */
public class PrincipalAdm extends javax.swing.JFrame {

   //ConexaoBD conecta = new ConexaoBD();
   
    public PrincipalAdm() {
        initComponents();
        //conecta.conexao();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAlterarSenha_PrincipalRecepcionista = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonEnfermeiro_PrincipalAdm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelGabiruLogo_PrincipalAdm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAlterarSenha_PrincipalRecepcionista1 = new javax.swing.JButton();
        jButtonSair_PrincipalAdm = new javax.swing.JButton();
        jLabelFundoPrincipalAdm = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jButtonAlterarSenha_PrincipalRecepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chave.png"))); // NOI18N
        jButtonAlterarSenha_PrincipalRecepcionista.setToolTipText("Alterar Senha");
        jButtonAlterarSenha_PrincipalRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarSenha_PrincipalRecepcionistaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/medico.png"))); // NOI18N
        jButton1.setToolTipText("Cadastro de Médicos");
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 80, 60, 60);

        jButtonEnfermeiro_PrincipalAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/enfermeiro222.png"))); // NOI18N
        jButtonEnfermeiro_PrincipalAdm.setToolTipText("Cadastro de Enfermeiros");
        jButtonEnfermeiro_PrincipalAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnfermeiro_PrincipalAdmActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEnfermeiro_PrincipalAdm);
        jButtonEnfermeiro_PrincipalAdm.setBounds(100, 80, 60, 60);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/paciente.png"))); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(530, 80, 60, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 110, 670, 220);

        jLabelGabiruLogo_PrincipalAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RAT7.png"))); // NOI18N
        jLabelGabiruLogo_PrincipalAdm.setToolTipText("Gabiru");
        getContentPane().add(jLabelGabiruLogo_PrincipalAdm);
        jLabelGabiruLogo_PrincipalAdm.setBounds(650, 0, 30, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ADM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 60, 20);

        jButtonAlterarSenha_PrincipalRecepcionista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chave.png"))); // NOI18N
        jButtonAlterarSenha_PrincipalRecepcionista1.setToolTipText("Alterar Senha");
        jButtonAlterarSenha_PrincipalRecepcionista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarSenha_PrincipalRecepcionista1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterarSenha_PrincipalRecepcionista1);
        jButtonAlterarSenha_PrincipalRecepcionista1.setBounds(20, 370, 40, 40);

        jButtonSair_PrincipalAdm.setText("Sair");
        getContentPane().add(jButtonSair_PrincipalAdm);
        jButtonSair_PrincipalAdm.setBounds(610, 380, 70, 30);

        jLabelFundoPrincipalAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agora.png"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipalAdm);
        jLabelFundoPrincipalAdm.setBounds(0, 0, 690, 420);
        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(708, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarSenha_PrincipalRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarSenha_PrincipalRecepcionistaActionPerformed
        AlterarSenha_recepcionista altsenha = new AlterarSenha_recepcionista();
        altsenha.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAlterarSenha_PrincipalRecepcionistaActionPerformed

    private void jButtonAlterarSenha_PrincipalRecepcionista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarSenha_PrincipalRecepcionista1ActionPerformed
        
    }//GEN-LAST:event_jButtonAlterarSenha_PrincipalRecepcionista1ActionPerformed

    private void jButtonEnfermeiro_PrincipalAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnfermeiro_PrincipalAdmActionPerformed
    FormularioEnfermeiro formenf = new FormularioEnfermeiro();
       formenf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonEnfermeiro_PrincipalAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAlterarSenha_PrincipalRecepcionista;
    private javax.swing.JButton jButtonAlterarSenha_PrincipalRecepcionista1;
    private javax.swing.JButton jButtonEnfermeiro_PrincipalAdm;
    private javax.swing.JButton jButtonSair_PrincipalAdm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundoPrincipalAdm;
    private javax.swing.JLabel jLabelGabiruLogo_PrincipalAdm;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
