/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Anderson
 */
public class PrincipalRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalRecepcionista
     */
    public PrincipalRecepcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAlterarSenha_PrincipalRecepcionista = new javax.swing.JButton();
        jPanelPrincipalRecepcionista = new javax.swing.JPanel();
        jButtonEmitirRelatorio_PrincipalRecepcionista = new javax.swing.JButton();
        jButtonCadastroPaciente_PrincipalRecepcionista = new javax.swing.JButton();
        jButtonAgendarConsulta_PrincipalRecepcionista = new javax.swing.JButton();
        jButtonSair_PrincipalRecepcionista = new javax.swing.JButton();
        jLabelBemVindo_PrincipalRecepcionista = new javax.swing.JLabel();
        jLabelGabiruLogo = new javax.swing.JLabel();
        jLabelSaudeSystemLogo = new javax.swing.JLabel();
        jLabelFundoAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonAlterarSenha_PrincipalRecepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chave.png"))); // NOI18N
        jButtonAlterarSenha_PrincipalRecepcionista.setToolTipText("Alterar Senha");
        jButtonAlterarSenha_PrincipalRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarSenha_PrincipalRecepcionistaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterarSenha_PrincipalRecepcionista);
        jButtonAlterarSenha_PrincipalRecepcionista.setBounds(410, 10, 40, 40);

        jPanelPrincipalRecepcionista.setLayout(null);

        jButtonEmitirRelatorio_PrincipalRecepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EmitirRelatorio.png"))); // NOI18N
        jButtonEmitirRelatorio_PrincipalRecepcionista.setToolTipText("Emitir Relatórios");
        jPanelPrincipalRecepcionista.add(jButtonEmitirRelatorio_PrincipalRecepcionista);
        jButtonEmitirRelatorio_PrincipalRecepcionista.setBounds(340, 80, 73, 70);

        jButtonCadastroPaciente_PrincipalRecepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadPaciente.png"))); // NOI18N
        jButtonCadastroPaciente_PrincipalRecepcionista.setToolTipText("Cadastrar Pacientes");
        jButtonCadastroPaciente_PrincipalRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroPaciente_PrincipalRecepcionistaActionPerformed(evt);
            }
        });
        jPanelPrincipalRecepcionista.add(jButtonCadastroPaciente_PrincipalRecepcionista);
        jButtonCadastroPaciente_PrincipalRecepcionista.setBounds(40, 80, 70, 70);

        jButtonAgendarConsulta_PrincipalRecepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AgendarConsulta.png"))); // NOI18N
        jButtonAgendarConsulta_PrincipalRecepcionista.setToolTipText("Agendar Consulta");
        jButtonAgendarConsulta_PrincipalRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarConsulta_PrincipalRecepcionistaActionPerformed(evt);
            }
        });
        jPanelPrincipalRecepcionista.add(jButtonAgendarConsulta_PrincipalRecepcionista);
        jButtonAgendarConsulta_PrincipalRecepcionista.setBounds(190, 80, 77, 70);

        jButtonSair_PrincipalRecepcionista.setText("Sair");
        jButtonSair_PrincipalRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSair_PrincipalRecepcionistaActionPerformed(evt);
            }
        });
        jPanelPrincipalRecepcionista.add(jButtonSair_PrincipalRecepcionista);
        jButtonSair_PrincipalRecepcionista.setBounds(360, 190, 70, 30);

        jLabelBemVindo_PrincipalRecepcionista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBemVindo_PrincipalRecepcionista.setText("Bem-Vindo, ");
        jPanelPrincipalRecepcionista.add(jLabelBemVindo_PrincipalRecepcionista);
        jLabelBemVindo_PrincipalRecepcionista.setBounds(10, 10, 150, 40);

        jLabelGabiruLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RAT7.png"))); // NOI18N
        jLabelGabiruLogo.setToolTipText("Gabiru");
        jPanelPrincipalRecepcionista.add(jLabelGabiruLogo);
        jLabelGabiruLogo.setBounds(0, 190, 30, 40);

        getContentPane().add(jPanelPrincipalRecepcionista);
        jPanelPrincipalRecepcionista.setBounds(10, 60, 440, 230);

        jLabelSaudeSystemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MENOR PRINCIPAL.png"))); // NOI18N
        getContentPane().add(jLabelSaudeSystemLogo);
        jLabelSaudeSystemLogo.setBounds(10, 0, 80, 60);

        jLabelFundoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundoAzul);
        jLabelFundoAzul.setBounds(-20, -10, 480, 330);

        setSize(new java.awt.Dimension(474, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroPaciente_PrincipalRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroPaciente_PrincipalRecepcionistaActionPerformed
       FormularioPaciente_recepcionista ff = new FormularioPaciente_recepcionista();
       ff.setVisible(true);
       dispose(); 
    }//GEN-LAST:event_jButtonCadastroPaciente_PrincipalRecepcionistaActionPerformed

    private void jButtonAgendarConsulta_PrincipalRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarConsulta_PrincipalRecepcionistaActionPerformed
        AgendarConsulta_recepcionista agend = new AgendarConsulta_recepcionista();
        agend.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAgendarConsulta_PrincipalRecepcionistaActionPerformed

    private void jButtonAlterarSenha_PrincipalRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarSenha_PrincipalRecepcionistaActionPerformed
      AlterarSenha_recepcionista altsenha = new AlterarSenha_recepcionista();
       altsenha.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonAlterarSenha_PrincipalRecepcionistaActionPerformed

    private void jButtonSair_PrincipalRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSair_PrincipalRecepcionistaActionPerformed
       Login lo = new Login();
       lo.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonSair_PrincipalRecepcionistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendarConsulta_PrincipalRecepcionista;
    private javax.swing.JButton jButtonAlterarSenha_PrincipalRecepcionista;
    private javax.swing.JButton jButtonCadastroPaciente_PrincipalRecepcionista;
    private javax.swing.JButton jButtonEmitirRelatorio_PrincipalRecepcionista;
    private javax.swing.JButton jButtonSair_PrincipalRecepcionista;
    private javax.swing.JLabel jLabelBemVindo_PrincipalRecepcionista;
    private javax.swing.JLabel jLabelFundoAzul;
    private javax.swing.JLabel jLabelGabiruLogo;
    private javax.swing.JLabel jLabelSaudeSystemLogo;
    private javax.swing.JPanel jPanelPrincipalRecepcionista;
    // End of variables declaration//GEN-END:variables
}
