/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author dell
 */
public class TelaPrincipalRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalRecepcionista
     */
    public TelaPrincipalRecepcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTela_PrincipalRecepcionista = new javax.swing.JLabel();
        jPanelTelaPrincipalRecepcionista = new javax.swing.JPanel();
        jButtonAgendarConsulta_TelaRecepcionista = new javax.swing.JButton();
        jButtonEmitirRelatorio_TelaRecepcionista = new javax.swing.JButton();
        jButtonCadPaciente_TelaRecepcionista = new javax.swing.JButton();
        jButtonSairTelaPrincipalRecepcionista = new javax.swing.JButton();
        jLabelLogoGabiru_TelaPrincipalRecepcionista = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(740, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 400));
        jPanel1.setLayout(null);

        jLabelTela_PrincipalRecepcionista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTela_PrincipalRecepcionista.setText("Bem-Vindo, ");
        jPanel1.add(jLabelTela_PrincipalRecepcionista);
        jLabelTela_PrincipalRecepcionista.setBounds(10, 10, 116, 29);

        jPanelTelaPrincipalRecepcionista.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTelaPrincipalRecepcionista.setLayout(null);

        jButtonAgendarConsulta_TelaRecepcionista.setText("Agendar Consulta");
        jButtonAgendarConsulta_TelaRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarConsulta_TelaRecepcionistaActionPerformed(evt);
            }
        });
        jPanelTelaPrincipalRecepcionista.add(jButtonAgendarConsulta_TelaRecepcionista);
        jButtonAgendarConsulta_TelaRecepcionista.setBounds(280, 150, 170, 40);

        jButtonEmitirRelatorio_TelaRecepcionista.setText("Emitir Relatório");
        jPanelTelaPrincipalRecepcionista.add(jButtonEmitirRelatorio_TelaRecepcionista);
        jButtonEmitirRelatorio_TelaRecepcionista.setBounds(280, 240, 170, 40);

        jButtonCadPaciente_TelaRecepcionista.setText("Cadastrar Paciente");
        jPanelTelaPrincipalRecepcionista.add(jButtonCadPaciente_TelaRecepcionista);
        jButtonCadPaciente_TelaRecepcionista.setBounds(280, 60, 170, 40);

        jButtonSairTelaPrincipalRecepcionista.setText("Sair");
        jButtonSairTelaPrincipalRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairTelaPrincipalRecepcionistaActionPerformed(evt);
            }
        });
        jPanelTelaPrincipalRecepcionista.add(jButtonSairTelaPrincipalRecepcionista);
        jButtonSairTelaPrincipalRecepcionista.setBounds(650, 310, 51, 23);

        jLabelLogoGabiru_TelaPrincipalRecepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/RAT7.png"))); // NOI18N
        jPanelTelaPrincipalRecepcionista.add(jLabelLogoGabiru_TelaPrincipalRecepcionista);
        jLabelLogoGabiru_TelaPrincipalRecepcionista.setBounds(10, 310, 30, 30);

        jPanel1.add(jPanelTelaPrincipalRecepcionista);
        jPanelTelaPrincipalRecepcionista.setBounds(10, 40, 720, 350);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2e8dd494ade012aa9bcb62519744b4a9.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgendarConsulta_TelaRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarConsulta_TelaRecepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgendarConsulta_TelaRecepcionistaActionPerformed

    private void jButtonSairTelaPrincipalRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairTelaPrincipalRecepcionistaActionPerformed
       TelaLogin.main(null);
        dispose();
    }//GEN-LAST:event_jButtonSairTelaPrincipalRecepcionistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendarConsulta_TelaRecepcionista;
    private javax.swing.JButton jButtonCadPaciente_TelaRecepcionista;
    private javax.swing.JButton jButtonEmitirRelatorio_TelaRecepcionista;
    private javax.swing.JButton jButtonSairTelaPrincipalRecepcionista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogoGabiru_TelaPrincipalRecepcionista;
    private javax.swing.JLabel jLabelTela_PrincipalRecepcionista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTelaPrincipalRecepcionista;
    // End of variables declaration//GEN-END:variables
}
