/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.DaoEnfermeiro;
import modelo.DaoExame;
import modelo.Enfermeiro;
import modelo.Exame;
import modelo.Medico;
import modelo.Paciente;


/**
 *
 * @author Anderson
 */
public class TelaExame extends javax.swing.JFrame {

    /**
     * Creates new form TelaExames
     */
    public TelaExame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSolicitarExame = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNomeMedico_SolicitarExame = new javax.swing.JLabel();
        jTextFieldNomeMedico_SolicitarExame = new javax.swing.JTextField();
        jLabelNomePaciente_SolicitarExame = new javax.swing.JLabel();
        jTextFieldNomePaciente_SolicitarExame = new javax.swing.JTextField();
        jLabelExames_SolicitarExames = new javax.swing.JLabel();
        jTextFieldExames_SolicitarExames = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabelSolicitarExame.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelSolicitarExame.setText("Solicitar Exame: ");
        getContentPane().add(jLabelSolicitarExame);
        jLabelSolicitarExame.setBounds(10, 0, 130, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabelNomeMedico_SolicitarExame.setText("Nome do Médico:");
        jPanel1.add(jLabelNomeMedico_SolicitarExame);
        jLabelNomeMedico_SolicitarExame.setBounds(10, 70, 100, 30);
        jPanel1.add(jTextFieldNomeMedico_SolicitarExame);
        jTextFieldNomeMedico_SolicitarExame.setBounds(120, 70, 590, 30);

        jLabelNomePaciente_SolicitarExame.setText("Nome da Paciente:");
        jPanel1.add(jLabelNomePaciente_SolicitarExame);
        jLabelNomePaciente_SolicitarExame.setBounds(10, 20, 110, 30);
        jPanel1.add(jTextFieldNomePaciente_SolicitarExame);
        jTextFieldNomePaciente_SolicitarExame.setBounds(120, 20, 590, 30);

        jLabelExames_SolicitarExames.setText("Exames:");
        jPanel1.add(jLabelExames_SolicitarExames);
        jLabelExames_SolicitarExames.setBounds(20, 120, 80, 30);
        jPanel1.add(jTextFieldExames_SolicitarExames);
        jTextFieldExames_SolicitarExames.setBounds(80, 130, 630, 220);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 373, 90, 30);

        jButton2.setText("Cancelar");
        jPanel1.add(jButton2);
        jButton2.setBounds(625, 373, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 730, 430);

        setSize(new java.awt.Dimension(769, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Exame exame = new Exame();
        DaoExame daoExame = new DaoExame();
        Medico medico = new Medico();
        Paciente paciente = new Paciente();
        
        if(!jTextFieldNomePaciente_SolicitarExame.getText().isEmpty() 
                || jTextFieldNomeMedico_SolicitarExame.getText().isEmpty()
                || jTextFieldExames_SolicitarExames.getText().isEmpty()
              
         ) {
            
           paciente.setNome(jTextFieldNomePaciente_SolicitarExame.getText());
           medico.setNome(jTextFieldNomeMedico_SolicitarExame.getText());
           exame.setNome(jTextFieldExames_SolicitarExames.getText());
            

           daoExame.adicionaExame(exame);
                      
        dispose();
        TelaPrincipal_Medico.main(null);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelExames_SolicitarExames;
    private javax.swing.JLabel jLabelNomeMedico_SolicitarExame;
    private javax.swing.JLabel jLabelNomePaciente_SolicitarExame;
    private javax.swing.JLabel jLabelSolicitarExame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldExames_SolicitarExames;
    private javax.swing.JTextField jTextFieldNomeMedico_SolicitarExame;
    private javax.swing.JTextField jTextFieldNomePaciente_SolicitarExame;
    // End of variables declaration//GEN-END:variables
}
