/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.DaoEnfermeiro;
import modelo.DaoExame;
import modelo.Enfermeiro;
import modelo.Exame;
import modelo.Medico;
import modelo.Paciente;

/**
 *
 * @author Anderson
 */
public class TelaExame extends javax.swing.JFrame {

    /**
     * Creates new form TelaExame
     */
    public TelaExame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSalvar_SolicitarExame = new javax.swing.JButton();
        jButtonCancelar_SolicitarExame = new javax.swing.JButton();
        jTextFieldNomeMedico_SolicitarExame = new javax.swing.JTextField();
        jTextFieldNomePaciente_SolicitarExame = new javax.swing.JTextField();
        jTextFieldExames_SolicitarExame = new javax.swing.JTextField();
        jLabelSolicitarExame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setText("Nome do Médico:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 14, 130, 20);

        jLabel2.setText("Nome do Paciente:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 130, 20);

        jLabel3.setText("Exames:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 90, 14);

        jButtonSalvar_SolicitarExame.setText("Salvar");
        jButtonSalvar_SolicitarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar_SolicitarExameActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar_SolicitarExame);
        jButtonSalvar_SolicitarExame.setBounds(510, 370, 80, 30);

        jButtonCancelar_SolicitarExame.setText("Cancelar");
        jButtonCancelar_SolicitarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar_SolicitarExameActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar_SolicitarExame);
        jButtonCancelar_SolicitarExame.setBounds(610, 370, 90, 30);
        jPanel1.add(jTextFieldNomeMedico_SolicitarExame);
        jTextFieldNomeMedico_SolicitarExame.setBounds(20, 40, 680, 30);
        jPanel1.add(jTextFieldNomePaciente_SolicitarExame);
        jTextFieldNomePaciente_SolicitarExame.setBounds(20, 90, 680, 30);
        jPanel1.add(jTextFieldExames_SolicitarExame);
        jTextFieldExames_SolicitarExame.setBounds(20, 150, 680, 180);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 44, 730, 430);

        jLabelSolicitarExame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSolicitarExame.setText("Solicitar Exame:");
        getContentPane().add(jLabelSolicitarExame);
        jLabelSolicitarExame.setBounds(20, 10, 130, 30);

        setSize(new java.awt.Dimension(769, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvar_SolicitarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvar_SolicitarExameActionPerformed
       Exame exame = new Exame();
       DaoExame daoExame = new DaoExame();
       Medico medico = new Medico();
       Paciente paciente =  new Paciente();
        
        if(!jTextFieldNomeMedico_SolicitarExame.getText().isEmpty()
           || !jTextFieldNomePaciente_SolicitarExame.getText().isEmpty()
           || !jTextFieldExames_SolicitarExame.getText().isEmpty()            
         ) {
            
            exame.setDescricao(jTextFieldExames_SolicitarExame.getText());
            medico.setNome(jTextFieldNomeMedico_SolicitarExame.getText());
            paciente.setNome(jTextFieldNomePaciente_SolicitarExame.getText());
                  

            try {
                daoExame.adicionaExame(exame, paciente, medico);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaExame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        dispose();
        TelaPrincipal_Medico.main(null);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos");
        }
    }//GEN-LAST:event_jButtonSalvar_SolicitarExameActionPerformed

    private void jButtonCancelar_SolicitarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar_SolicitarExameActionPerformed
        TelaPrincipal_Medico.main(null);
        dispose();
    }//GEN-LAST:event_jButtonCancelar_SolicitarExameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar_SolicitarExame;
    private javax.swing.JButton jButtonSalvar_SolicitarExame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelSolicitarExame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldExames_SolicitarExame;
    private javax.swing.JTextField jTextFieldNomeMedico_SolicitarExame;
    private javax.swing.JTextField jTextFieldNomePaciente_SolicitarExame;
    // End of variables declaration//GEN-END:variables
}
