/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author dell
 */
public class TelaGerarCobrança extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerarCobrança
     */
    public TelaGerarCobrança() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTelaGerarCobrança = new javax.swing.JLabel();
        jLabelNomePaciente_TelaGerarCobranca = new javax.swing.JLabel();
        jTextFieldNomePaciente_TelaGerarCobranca = new javax.swing.JTextField();
        jLabelCPF_TelaGerarCobranca = new javax.swing.JLabel();
        jTextFieldCPF_TelaGerarCobranca = new javax.swing.JTextField();
        jLabelValorConranca_TelaGerarCobranca = new javax.swing.JLabel();
        jTextFieldValorConranca_TelaGerarCobranca = new javax.swing.JTextField();
        jLabelNomeMedico_TelaGerarConsulta = new javax.swing.JLabel();
        jTextFieldNomeMedico_TelaGerarCobranca = new javax.swing.JTextField();
        jLabelEspecialidadeMedica_TelaGerarCobranca = new javax.swing.JLabel();
        jTextFieldEspecialidadeMedica_TelaGerarCobranca = new javax.swing.JTextField();
        jButtonFinalizar_TelaGerarCobranca = new javax.swing.JButton();
        jButtonCancelar_TelaGerarCobranca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 400));
        setPreferredSize(new java.awt.Dimension(750, 400));

        jPanel1.setMinimumSize(new java.awt.Dimension(740, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 400));

        jLabelTelaGerarCobrança.setText("Gerar Cobrança");

        jLabelNomePaciente_TelaGerarCobranca.setText("Nome do Paciente");

        jLabelCPF_TelaGerarCobranca.setText("CPF");

        jLabelValorConranca_TelaGerarCobranca.setText("Valor da cobrança");

        jLabelNomeMedico_TelaGerarConsulta.setText("Nome do Médico");

        jLabelEspecialidadeMedica_TelaGerarCobranca.setText("Especialidade");

        jButtonFinalizar_TelaGerarCobranca.setText("Finalizar");

        jButtonCancelar_TelaGerarCobranca.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(299, 299, 299)
                                .addComponent(jLabelTelaGerarCobrança, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelNomePaciente_TelaGerarCobranca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomePaciente_TelaGerarCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelCPF_TelaGerarCobranca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCPF_TelaGerarCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelNomeMedico_TelaGerarConsulta)
                                .addGap(19, 19, 19)
                                .addComponent(jTextFieldNomeMedico_TelaGerarCobranca)))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonFinalizar_TelaGerarCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar_TelaGerarCobranca)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelEspecialidadeMedica_TelaGerarCobranca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEspecialidadeMedica_TelaGerarCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelValorConranca_TelaGerarCobranca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorConranca_TelaGerarCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTelaGerarCobrança, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomePaciente_TelaGerarCobranca)
                            .addComponent(jTextFieldNomePaciente_TelaGerarCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCPF_TelaGerarCobranca)
                            .addComponent(jTextFieldCPF_TelaGerarCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNomeMedico_TelaGerarConsulta))
                    .addComponent(jTextFieldNomeMedico_TelaGerarCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEspecialidadeMedica_TelaGerarCobranca)
                    .addComponent(jTextFieldEspecialidadeMedica_TelaGerarCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorConranca_TelaGerarCobranca)
                    .addComponent(jTextFieldValorConranca_TelaGerarCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFinalizar_TelaGerarCobranca)
                    .addComponent(jButtonCancelar_TelaGerarCobranca))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerarCobrança.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerarCobrança.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerarCobrança.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerarCobrança.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerarCobrança().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar_TelaGerarCobranca;
    private javax.swing.JButton jButtonFinalizar_TelaGerarCobranca;
    private javax.swing.JLabel jLabelCPF_TelaGerarCobranca;
    private javax.swing.JLabel jLabelEspecialidadeMedica_TelaGerarCobranca;
    private javax.swing.JLabel jLabelNomeMedico_TelaGerarConsulta;
    private javax.swing.JLabel jLabelNomePaciente_TelaGerarCobranca;
    private javax.swing.JLabel jLabelTelaGerarCobrança;
    private javax.swing.JLabel jLabelValorConranca_TelaGerarCobranca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCPF_TelaGerarCobranca;
    private javax.swing.JTextField jTextFieldEspecialidadeMedica_TelaGerarCobranca;
    private javax.swing.JTextField jTextFieldNomeMedico_TelaGerarCobranca;
    private javax.swing.JTextField jTextFieldNomePaciente_TelaGerarCobranca;
    private javax.swing.JTextField jTextFieldValorConranca_TelaGerarCobranca;
    // End of variables declaration//GEN-END:variables
}
