/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author dell
 */
public class TelaPrincipalRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalRecepcionista
     */
    public TelaPrincipalRecepcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCadPaciente_TelaRecepcionista = new javax.swing.JButton();
        jButtonAgendarConsulta_TelaRecepcionista = new javax.swing.JButton();
        jButtonEmitirRelatorio_TelaRecepcionista = new javax.swing.JButton();
        jLabelTela_PrincipalRecepcionista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(740, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 400));
        jPanel1.setLayout(null);

        jButtonCadPaciente_TelaRecepcionista.setText("Cadastrar Paciente");
        jPanel1.add(jButtonCadPaciente_TelaRecepcionista);
        jButtonCadPaciente_TelaRecepcionista.setBounds(250, 40, 160, 50);

        jButtonAgendarConsulta_TelaRecepcionista.setText("Agendar Consulta");
        jButtonAgendarConsulta_TelaRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarConsulta_TelaRecepcionistaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgendarConsulta_TelaRecepcionista);
        jButtonAgendarConsulta_TelaRecepcionista.setBounds(500, 40, 160, 50);

        jButtonEmitirRelatorio_TelaRecepcionista.setText("Emitir Relatório");
        jPanel1.add(jButtonEmitirRelatorio_TelaRecepcionista);
        jButtonEmitirRelatorio_TelaRecepcionista.setBounds(20, 30, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 44, 740, 400);

        jLabelTela_PrincipalRecepcionista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTela_PrincipalRecepcionista.setText("Bem-Vindo, ");
        getContentPane().add(jLabelTela_PrincipalRecepcionista);
        jLabelTela_PrincipalRecepcionista.setBounds(20, 10, 116, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgendarConsulta_TelaRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarConsulta_TelaRecepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgendarConsulta_TelaRecepcionistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendarConsulta_TelaRecepcionista;
    private javax.swing.JButton jButtonCadPaciente_TelaRecepcionista;
    private javax.swing.JButton jButtonEmitirRelatorio_TelaRecepcionista;
    private javax.swing.JLabel jLabelTela_PrincipalRecepcionista;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
